"""empty message

Revision ID: 0cb7be09b140
Revises: 5639da68f9e8
Create Date: 2022-05-31 09:39:26.808831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb7be09b140'
down_revision = '5639da68f9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'entry', 'entry', ['project_id'], ['project_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.drop_column('entry', 'project_id')
    # ### end Alembic commands ###
