"""empty message

Revision ID: 3039e0eb09b4
Revises: 6641779183e7
Create Date: 2022-06-20 18:41:53.920384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3039e0eb09b4'
down_revision = '6641779183e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('sequence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'sequence')
    # ### end Alembic commands ###
