"""empty message

Revision ID: 4d1d7cc26dde
Revises: 0cb7be09b140
Create Date: 2022-05-31 11:43:32.307336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1d7cc26dde'
down_revision = '0cb7be09b140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'entry', 'project', ['project_id'], ['project_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='foreignkey')
    # ### end Alembic commands ###
