"""empty message

Revision ID: 6641779183e7
Revises: 
Create Date: 2022-06-03 19:03:30.145381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6641779183e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('is_split', sa.Boolean(), nullable=True),
    sa.Column('is_binarized', sa.Boolean(), nullable=True),
    sa.Column('has_gaps', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threshold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h_width', sa.Float(), nullable=True),
    sa.Column('h_blank', sa.Float(), nullable=True),
    sa.Column('v_width', sa.Float(), nullable=True),
    sa.Column('v_blank', sa.Float(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('ignore_start', sa.Integer(), nullable=True),
    sa.Column('ignore_end', sa.Integer(), nullable=True),
    sa.Column('ignore_left', sa.Integer(), nullable=True),
    sa.Column('ignore_right', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bounding_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('w', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whitespace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('threshold_id', sa.Integer(), nullable=False),
    sa.Column('annotation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['threshold_id'], ['threshold.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whitespace_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['whitespace_id'], ['whitespace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gap')
    op.drop_table('whitespace')
    op.drop_table('bounding_box')
    op.drop_table('page')
    op.drop_table('entry')
    op.drop_table('threshold')
    op.drop_table('project')
    # ### end Alembic commands ###
