"""empty message

Revision ID: 6b4645d1ae14
Revises: 4d1d7cc26dde
Create Date: 2022-06-01 16:01:25.661662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4645d1ae14'
down_revision = '4d1d7cc26dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'entry', 'project', ['project_id'], ['id'])
    op.add_column('gap', sa.Column('whitespace_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'gap', type_='foreignkey')
    op.create_foreign_key(None, 'gap', 'whitespace', ['whitespace_id'], ['id'])
    op.drop_column('gap', 'page_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gap', sa.Column('page_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'gap', type_='foreignkey')
    op.create_foreign_key(None, 'gap', 'whitespace', ['page_id'], ['id'])
    op.drop_column('gap', 'whitespace_id')
    op.drop_constraint(None, 'entry', type_='foreignkey')
    # ### end Alembic commands ###
