"""empty message

Revision ID: 861cb4e37250
Revises: 3039e0eb09b4
Create Date: 2022-06-20 23:31:43.434195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861cb4e37250'
down_revision = '3039e0eb09b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'name')
    # ### end Alembic commands ###
