version: '3.8'

services:
  pdf-tools:
    build: .
    container_name: pdf-tools
    ports:
      - "5000:5000"
    # command: python -m flask run --host=0.0.0.0 # change command here if needed!
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    volumes:
      - ./:/app
    depends_on: ["redis", "celery"]   # gotta have the queue running first!


  celery:
    build: .
    container_name: celery
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    volumes:
      - ./:/app
    command: celery --app interface.celery worker --loglevel=info
    depends_on: [ "redis" ]  # gotta have the queue running first!


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis


  flower-dashboard:
    build: .
    container_name: flower-dashboard
    command: celery --app interface.celery flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    volumes:
        - ./:/app
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on: ["redis", "celery"]